<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <Description>An in-memory implementation for Azure Table Storage useful for testing and local development.</Description>
    <Authors>Andrei Fangli</Authors>
    <Copyright>Andrei Fangli</Copyright>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>logo.png</PackageIcon>
    <PackageTags>stub;azure;storage;memory;in-memory;test</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Andrei15193/CloudStub.git</RepositoryUrl>
    <BaseVersion>1.0.0-alpha.0</BaseVersion>
    <PackageReleaseNotes>
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
  </ItemGroup>
</Project>
