<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <Description>An in-memory implementation for Azure Table Storage useful for testing and local development.</Description>
    <Authors>Andrei Fangli</Authors>
    <Copyright>Andrei Fangli</Copyright>
    <PackageTags>stub;azure;storage;memory;in-memory;test</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageProjectUrl>https://github.com/Andrei15193/CloudStub.AzureDataTables</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/Andrei15193/CloudStub.AzureDataTables.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
  </ItemGroup>
</Project>
